- update RetroArch to version 1.15.0 - remove retroarch binary from rootfs - revert /etc/init.d/S49usbdevice - update libmali-utgard-400

diff --git a/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch b/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
--- a/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
+++ b/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
@@ -3,8 +3,8 @@
 case "$1" in
   start)
     export XDG_CONFIG_HOME=/mnt/sdcard
-    export ROMS_HOME=/mnt/sdcard/roms # directory to start scan content in RetroArch
-    { { /retroarch/retroarch -v --log-file /dev/console && halt; } || echo "TODO: handle error"; } &
+    export ROMS_HOME=/mnt/sdcard/roms # start directory to scan content in RetroArch
+    { { /mnt/sdcard/retroarch/retroarch -v --log-file /dev/console && halt; } || echo "TODO: handle error"; } &
     ;;
   stop)
     killall -9 retroarch
