simplify init.d script for retroarch

diff --git a/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch b/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
--- a/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
+++ b/devices/gamesticklite-v5/files/etc/init.d/S90-retroarch
@@ -2,9 +2,7 @@
 
 case "$1" in
   start)
-    export XDG_CONFIG_HOME=/mnt/sdcard
-    export ROMS_HOME=/mnt/sdcard/roms # start directory to scan content in RetroArch
-    { { /mnt/sdcard/retroarch/retroarch -v --log-file /dev/console && halt; } || echo "TODO: handle error"; } &
+    { { /mnt/sdcard/retroarch/start.sh && halt; } || echo "TODO: handle error"; } &
     ;;
   stop)
     killall -9 retroarch
